class_name Constants
extends Node

const PLAYER_BUSINESSES = 'businesses'
const PLAYER_FAMILY_1_RESPECT = 'family_1_respect'
const PLAYER_FAMILY_2_RESPECT = 'family_2_respect'
const PLAYER_HEAT = 'heat'
const PLAYER_INCOME = 'income'
const PLAYER_JOB = 'job'
const PLAYER_LOANS = 'loans'
const PLAYER_MONEY = 'money'
const PLAYER_RENTALS = 'rentals'
const PLAYER_SANITY = 'sanity'
const PLAYER_STREET_SMART = 'street_smart'
const PLAYER_TERRITORIES_RESPECT = 'territories_respect'

const EVENT_BANK_OFFERS_LOAN = 'event_bank_offers_loan'
const EVENT_FAMILY_1_OFFERS_LOAN = 'event_family_1_offers_loan'
const EVENT_FAMILY_1_OFFERS_WORK = 'event_family_1_offers_work'
const EVENT_FAMILY_1_WANTS_HELP_ROBBING_YOUR_JOB = 'event_family_1_wants_help_robbing_your_job'
const EVENT_FAMILY_1_WANTS_TO_EXTORT_BUSINESS = 'event_family_1_wants_to_extort_business'
const EVENT_FAMILY_1_WANTS_TO_LAUNDER_THROUGH_BUSINESS = 'event_family_1_wants_to_launder_through_business'
const EVENT_FAMILY_1_WANTS_TO_USE_BUSINESS_TO_COVER_CRIME = 'event_family_1_wants_to_use_business_to_cover_crime'
const EVENT_FAMILY_2_OFFERS_LOAN = 'event_family_2_offers_loan'
const EVENT_FAMILY_2_OFFERS_WORK = 'event_family_2_offers_work'
const EVENT_FAMILY_2_WANTS_HELP_ROBBING_YOUR_JOB = 'event_family_2_wants_help_robbing_your_job'
const EVENT_FAMILY_2_WANTS_TO_EXTORT_BUSINESS = 'event_family_2_wants_to_extort_business'
const EVENT_FAMILY_2_WANTS_TO_LAUNDER_THROUGH_BUSINESS = 'event_family_2_wants_to_launder_through_business'
const EVENT_FAMILY_2_WANTS_TO_USE_BUSINESS_TO_COVER_CRIME = 'event_family_2_wants_to_use_business_to_cover_crime'
const EVENT_FEDS_WANT_PROOF_OF_INCOME = 'event_feds_want_proof_of_income'
const EVENT_HANDLE_GETTING_ARRESTED = 'event_handle_getting_arrested'
const EVENT_HIT_ATTEMPTED_BY_FAMILY_1 = 'event_hit_attempted_by_family_1'
const EVENT_HIT_ATTEMPTED_BY_FAMILY_2 = 'event_hit_attempted_by_family_2'
const EVENT_PROVIDE_INFO_ON_FAMILY_TO_POLICE = 'event_provide_info_on_family_to_police'
const EVENT_ROBBED_BY_FAMILY_1 = 'event_robbed_by_family_1'
const EVENT_ROBBED_BY_FAMILY_2 = 'event_robbed_by_family_2'
const EVENT_ROBBED_BY_STREET_GANG = 'event_robbed_by_street_gang'
const EVENT_SABOTAGE_RIVAL_FAMILY = 'event_sabotage_rival_family'
const EVENT_STAND_UP_TO_FAMILY_1 = 'event_stand_up_to_family_1'
const EVENT_STAND_UP_TO_FAMILY_2 = 'event_stand_up_to_family_2'
const EVENT_STAND_UP_TO_STREET_GANG = 'event_stand_up_to_street_gang'
const EVENT_TAKE_THE_FALL_FOR_FAMILY_1 = 'event_take_the_fall_for_family_1'
const EVENT_TAKE_THE_FALL_FOR_FAMILY_2 = 'event_take_the_fall_for_family_2'

const TRIGGER_ARRESTED = 'trigger_arrested'
const TRIGGER_BRIBE_JURY = 'trigger_bribe_jury'
const TRIGGER_SERVE_JAIL_TIME = 'trigger_serve_jail_time'
const TRIGGER_THREATEN_JURY = 'trigger_threaten_jury'
const TRIGGER_WORKING_FOR_FAMILY_1 = 'trigger_working_for_family_1'
